--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12/11/2022 7:25:46 AM
-- Target server version: 8.0.21
-- Target connection string: User Id=root;Host=localhost;Character Set=utf8
--



SET NAMES 'utf8';
USE gymerinfo;
--
-- Delete data from the table 'gymerneed'
--
TRUNCATE TABLE gymerneed;

--
-- Inserting data into table gymerneed
--
INSERT INTO gymerneed(ID, gender, age, bmi, workOutFrequence, workPlace, target, focusedArea, experiencedYear) VALUES
(1, 'Nam', 49, 'Overweight', 'từ 4 đến 5 lần/ tuần', 'tại nhà', 'tăng sức bền', 'thân dưới', 'dưới 1 năm'),
(2, 'Nam', 26, 'Overweight', 'dưới 4 lần/ tuần', 'tài phòng gym', 'tăng sức bền', 'thân dưới', 'dưới 1 năm'),
(3, 'Nữ', 55, 'Overweight', 'dưới 4 lần/ tuần', 'tài phòng gym', 'giảm mỡ', 'thân dưới', 'dưới 1 năm'),
(4, 'Nam', 17, 'Underweight', 'trên 5 lần/ tuần', 'tại nhà', 'giảm mỡ', 'toàn thân', '1 đến 2 năm'),
(5, 'Nam', 26, 'Underweight', 'dưới 4 lần/ tuần', 'tài phòng gym', 'tăng cơ', 'vùng cơ trung tâm', '1 đến 2 năm'),
(6, 'Nam', 37, 'Overweight', 'dưới 4 lần/ tuần', 'tại nhà', 'tăng cơ', 'toàn thân', 'dưới 1 năm'),
(7, 'Nam', 60, 'Overweight', 'trên 5 lần/ tuần', 'tại nhà', 'giảm mỡ', 'thân trên', 'dưới 1 năm'),
(8, 'Nam', 43, 'Good', 'dưới 4 lần/ tuần', 'tài phòng gym', 'giảm mỡ', 'toàn thân', 'trên 2 năm'),
(9, 'Nữ', 53, 'Overweight', 'dưới 4 lần/ tuần', 'tại nhà', 'giảm mỡ', 'vùng cơ trung tâm', 'dưới 1 năm'),
(10, 'Nam', 18, 'Underweight', 'dưới 4 lần/ tuần', 'tại nhà', 'tăng sức bền', 'thân trên', '1 đến 2 năm'),
(11, 'Nữ', 49, 'Overweight', 'từ 4 đến 5 lần/ tuần', 'tài phòng gym', 'tăng cơ', 'toàn thân', 'dưới 1 năm'),
(12, 'Nam', 47, 'Overweight', 'dưới 4 lần/ tuần', 'tài phòng gym', 'giảm mỡ', 'thân dưới', 'dưới 1 năm'),
(13, 'Nam', 54, 'Overweight', 'dưới 4 lần/ tuần', 'tài phòng gym', 'giảm mỡ', 'thân trên', 'dưới 1 năm'),
(14, 'Nam', 30, 'Good', 'từ 4 đến 5 lần/ tuần', 'tại nhà', 'giảm mỡ', 'thân trên', 'trên 2 năm'),
(15, 'Nữ', 60, 'Underweight', 'dưới 4 lần/ tuần', 'tại nhà', 'tăng sức bền', 'vùng cơ trung tâm', '1 đến 2 năm'),
(16, 'Nữ', 56, 'Underweight', 'dưới 4 lần/ tuần', 'tài phòng gym', 'giảm mỡ', 'thân trên', '1 đến 2 năm'),
(17, 'Nữ', 34, 'Overweight', 'từ 4 đến 5 lần/ tuần', 'tại nhà', 'giảm mỡ', 'toàn thân', 'dưới 1 năm'),
(18, 'Nữ', 38, 'Underweight', 'dưới 4 lần/ tuần', 'tài phòng gym', 'giảm mỡ', 'thân trên', '1 đến 2 năm'),
(19, 'Nam', 43, 'Underweight', 'từ 4 đến 5 lần/ tuần', 'tài phòng gym', 'tăng sức bền', 'toàn thân', '1 đến 2 năm'),
(20, 'Nữ', 27, 'Underweight', 'dưới 4 lần/ tuần', 'tại nhà', 'tăng sức bền', 'thân dưới', '1 đến 2 năm'),
(21, 'Nữ', 23, 'Good', 'dưới 4 lần/ tuần', 'tại nhà', 'giảm mỡ', 'vùng cơ trung tâm', 'trên 2 năm'),
(22, 'Nữ', 44, 'Overweight', 'dưới 4 lần/ tuần', 'tài phòng gym', 'tăng sức bền', 'thân trên', 'dưới 1 năm'),
(23, 'Nam', 26, 'Overweight', 'dưới 4 lần/ tuần', 'tại nhà', 'giảm mỡ', 'toàn thân', 'dưới 1 năm'),
(24, 'Nữ', 26, 'Overweight', 'từ 4 đến 5 lần/ tuần', 'tại nhà', 'giảm mỡ', 'toàn thân', 'dưới 1 năm'),
(25, 'Nữ', 24, 'Underweight', 'trên 5 lần/ tuần', 'tài phòng gym', 'tăng cơ', 'thân trên', '1 đến 2 năm'),
(26, 'Nam', 27, 'Overweight', 'trên 5 lần/ tuần', 'tại nhà', 'tăng cơ', 'toàn thân', 'dưới 1 năm'),
(27, 'Nam', 44, 'Underweight', 'từ 4 đến 5 lần/ tuần', 'tài phòng gym', 'giảm mỡ', 'thân dưới', '1 đến 2 năm'),
(28, 'Nam', 38, 'Overweight', 'trên 5 lần/ tuần', 'tài phòng gym', 'tăng cơ', 'toàn thân', 'dưới 1 năm'),
(29, 'Nữ', 17, 'Good', 'dưới 4 lần/ tuần', 'tại nhà', 'giảm mỡ', 'toàn thân', 'trên 2 năm'),
(30, 'Nam', 38, 'Good', 'từ 4 đến 5 lần/ tuần', 'tại nhà', 'giảm mỡ', 'thân trên', 'trên 2 năm'),
(31, 'Nam', 55, 'Underweight', 'trên 5 lần/ tuần', 'tại nhà', 'giảm mỡ', 'thân trên', '1 đến 2 năm'),
(32, 'Nam', 58, 'Underweight', 'trên 5 lần/ tuần', 'tại nhà', 'giảm mỡ', 'toàn thân', '1 đến 2 năm'),
(33, 'Nữ', 34, 'Underweight', 'dưới 4 lần/ tuần', 'tài phòng gym', 'tăng sức bền', 'thân dưới', '1 đến 2 năm'),
(34, 'Nam', 52, 'Overweight', 'dưới 4 lần/ tuần', 'tại nhà', 'tăng cơ', 'thân trên', 'dưới 1 năm'),
(35, 'Nam', 25, 'Good', 'dưới 4 lần/ tuần', 'tài phòng gym', 'tăng cơ', 'thân dưới', 'trên 2 năm'),
(36, 'Nam', 50, 'Good', 'trên 5 lần/ tuần', 'tài phòng gym', 'tăng sức bền', 'toàn thân', 'trên 2 năm'),
(37, 'Nam', 50, 'Good', 'từ 4 đến 5 lần/ tuần', 'tài phòng gym', 'giảm mỡ', 'thân trên', 'trên 2 năm'),
(38, 'Nam', 25, 'Overweight', 'từ 4 đến 5 lần/ tuần', 'tại nhà', 'tăng cơ', 'toàn thân', 'dưới 1 năm'),
(39, 'Nam', 22, 'Underweight', 'từ 4 đến 5 lần/ tuần', 'tài phòng gym', 'tăng cơ', 'thân trên', '1 đến 2 năm'),
(40, 'Nữ', 24, 'Underweight', 'dưới 4 lần/ tuần', 'tài phòng gym', 'tăng cơ', 'toàn thân', '1 đến 2 năm'),
(41, 'Nữ', 22, 'Overweight', 'dưới 4 lần/ tuần', 'tài phòng gym', 'giảm mỡ', 'thân dưới', 'dưới 1 năm'),
(42, 'Nam', 26, 'Good', 'dưới 4 lần/ tuần', 'tài phòng gym', 'tăng sức bền', 'thân trên', 'trên 2 năm'),
(43, 'Nam', 54, 'Underweight', 'dưới 4 lần/ tuần', 'tài phòng gym', 'giảm mỡ', 'toàn thân', '1 đến 2 năm'),
(44, 'Nam', 33, 'Overweight', 'dưới 4 lần/ tuần', 'tài phòng gym', 'giảm mỡ', 'toàn thân', 'dưới 1 năm'),
(45, 'Nam', 34, 'Overweight', 'trên 5 lần/ tuần', 'tại nhà', 'tăng cơ', 'vùng cơ trung tâm', 'dưới 1 năm'),
(46, 'Nam', 20, 'Underweight', 'từ 4 đến 5 lần/ tuần', 'tại nhà', 'giảm mỡ', 'thân trên', '1 đến 2 năm'),
(47, 'Nam', 56, 'Underweight', 'dưới 4 lần/ tuần', 'tại nhà', 'giảm mỡ', 'thân trên', '1 đến 2 năm'),
(48, 'Nam', 46, 'Overweight', 'dưới 4 lần/ tuần', 'tài phòng gym', 'giảm mỡ', 'vùng cơ trung tâm', 'dưới 1 năm'),
(49, 'Nữ', 35, 'Overweight', 'dưới 4 lần/ tuần', 'tại nhà', 'giảm mỡ', 'toàn thân', 'dưới 1 năm'),
(50, 'Nam', 19, 'Overweight', 'dưới 4 lần/ tuần', 'tài phòng gym', 'tăng sức bền', 'toàn thân', 'dưới 1 năm');